#! /bin/sh

# Start sxhkd if not already started
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X
bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Use wmname to display content of java applications
wmname LG3D

# Stop and restart lemonbar
pkill -x lemonbar > /dev/null
pkill -x lemonbar.sh > /dev/null
"$HOME"/.config/lemonbar/lemonbar.sh | lemonbar -p -f 'Jetbrains Mono' -f 'Font Awesome 6 Free Solid' | "$HOME"/.config/lemonbar/exec_cmd.sh &

# Start gnome-keyring
gnome-keyring-daemon --start
export SSH_AUTH_SOCK
