#! /bin/sh

# Start sxhkd if not already started
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DisplayPort-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set rules because firefox-nightly doesnt tile by default
bspc rule -a WebApp-Twitch4406 state=tiled
bspc rule -a FirefoxNightly state=tiled
 
# Use wmname to display content of java applications
wmname LG3D

# Stop and restart lemonbar

#pkill -x lemonbar.sh > /dev/null
#"$HOME"/.config/lemonbar/lemonbar.sh | lemonbar -p -f 'Jetbrains Mono' -f 'Font Awesome 6 Free Solid' | "$HOME"/.config/lemonbar/exec_cmd.sh &

killall -q polybar
polybar mybar 2>&1 | tee -a /tmp/polybar.log & disown

# Stop and restart playerctl daemon
#pkill -x playerctld
#playerctld daemon &

# Start gnome-keyring
gnome-keyring-daemon --start
export SSH_AUTH_SOCK

# Start kde-connect
pgrep -x kdeconnectd > /dev/null || /usr/lib/kdeconnectd &
